# Basic Configuration
title: "GoogleAlgoJourney"
description: "A portfolio exploring Google algorithms."






theme: slate
highlighter: rouge  




markdown: kramdown


paginate: 5




footer_text: "© 2025 GoogleAlgoJourney. All rights reserved."



